"""Exceptions package."""
from gatehouse_app.exceptions.base import BaseAPIException
from gatehouse_app.exceptions.auth_exceptions import (
    UnauthorizedError,
    ForbiddenError,
    InvalidCredentialsError,
    AccountSuspendedError,
    AccountInactiveError,
    SessionExpiredError,
    InvalidTokenError,
)
from gatehouse_app.exceptions.validation_exceptions import (
    ValidationError,
    NotFoundError,
    ConflictError,
    BadRequestError,
    RateLimitExceededError,
    EmailAlreadyExistsError,
    OrganizationNotFoundError,
    UserNotFoundError,
)
from gatehouse_app.exceptions.ssh_exceptions import (
    SSHCAError,
    SSHKeyError,
    SSHKeyNotFoundError,
    SSHKeyAlreadyExistsError,
    SSHKeyNotVerifiedError,
    SSHCertificateError,
    SSHCertificateNotFoundError,
    CAError,
    CANotFoundError,
    PrincipalError,
    PrincipalNotFoundError,
    DepartmentError,
    DepartmentNotFoundError,
)

__all__ = [
    "BaseAPIException",
    "UnauthorizedError",
    "ForbiddenError",
    "InvalidCredentialsError",
    "AccountSuspendedError",
    "AccountInactiveError",
    "SessionExpiredError",
    "InvalidTokenError",
    "ValidationError",
    "NotFoundError",
    "ConflictError",
    "BadRequestError",
    "RateLimitExceededError",
    "EmailAlreadyExistsError",
    "OrganizationNotFoundError",
    "UserNotFoundError",
    "SSHCAError",
    "SSHKeyError",
    "SSHKeyNotFoundError",
    "SSHKeyAlreadyExistsError",
    "SSHKeyNotVerifiedError",
    "SSHCertificateError",
    "SSHCertificateNotFoundError",
    "CAError",
    "CANotFoundError",
    "PrincipalError",
    "PrincipalNotFoundError",
    "DepartmentError",
    "DepartmentNotFoundError",
]

